// layout.tsx
import { Suspense } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import LoadingAnimation from "./loading";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navTitles = [
    { label: 'Practices', path: '/Practices' },
    { label: 'Contests', path: '/Contests' },
    { label: 'Games', path: '/Games' },
    { label: 'Pricing', path: '/Pricing' },
    { label: 'FAQs', path: '/FAQ' },
  ];
  
  return (
    <html lang="en">
      <body className="two-line-bg">
        <Navbar titles={navTitles}></Navbar> 
        
        <ToastContainer />

        {children}
     
        <Footer></Footer>
      </body>
    </html>
  );
}
