import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navTitles = [
    { label: 'Practices', path: '/Practices' },
    { label: 'Contests', path: '/Contests' },
    { label: 'Games', path: '/Games' },
    { label: 'Pricing', path: '/Pricing' },
    { label: 'FAQ', path: '/FAQ' },
  ];
  
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Navbar titles={navTitles}></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
