const cacheTypes = {
  PREV_WEEK_TOP_STORIES: "PREV_WEEK_TOP_STORIES",
  PRACTISE_PROMPTS: "PRACTISE_PROMPTS",
  ONGOING_CONTEST: "ONGOING_CONTEST",
  ENDED_CONTEST: "ENDED_CONTEST",
  GAME_PROMPT: "GAME_PROMPT",
  SUBSCRIPTION_DATA: "SUBSCRIPTION_DATA",
};

module.exports = cacheTypes;
