name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull the Docker Image - frontend
      run: sudo docker pull skilledsantoshh/test:writeasy_frontend

    - name: Delete the old Docker Container - frontend
      run: sudo docker rm -f writeasy_frontend_container || true

    - name: Run the Docker Container - frontend
      run: sudo docker run -d -p 3000:3000 --name writeasy_frontend_container skilledsantoshh/test:writeasy_frontend

    - name: Pull the Docker Image - backend
      run: sudo docker pull skilledsantoshh/test:writeasy_backend
    
    - name: Delete the old Docker Container - backend
      run: sudo docker rm -f writeasy_backend_container || true

    - name: Run the Docker Container - backend
      run: sudo docker run -d -p 8000:8000 --name writeasy_backend_container skilledsantoshh/test:writeasy_backend