name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop and Remove Old Containers and Images using Docker Compose
        run: |
          cd ../../  # Change this to the actual path where docker-compose.yml is located
          sudo docker-compose down || true  # Stop and remove old containers
          sudo docker-compose rm -f || true # Force remove old containers (if any left)

      - name: Pull and Start Services using Docker Compose
        run: |
          cd ../../  
          sudo docker-compose pull  # Pull the latest images from Docker Hub
          sudo docker-compose up -d --build  # Build and start services in detached mode
