name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build docker image - frontend
        run: |
          docker buildx build --build-arg NODE_IMAGE=node:18.17.0-alpine \
                              --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=${{secrets.NEXT_PUBLIC_FIREBASE_API_KEY}} \
                              --build-arg NEXT_PUBLIC_BACKEND_ROOT_URL=${{secrets.NEXT_PUBLIC_BACKEND_ROOT_URL}} \
                              -t skilledsantoshh/test:writeasy_frontend ./frontend
                              
      - name: Build docker image - backend
        run: |
          docker buildx build --build-arg NODE_IMAGE=node:18.17.0-alpine \
                              -t skilledsantoshh/test:writeasy_backend ./backend

      - name: Push docker image to docker hub - frontend
        run: docker push skilledsantoshh/test:writeasy_frontend         

      - name: Push docker image to docker hub - backend
        run: docker push skilledsantoshh/test:writeasy_backend
